version: "3"
services:
  activity:
    container_name: Activity
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /activity
    volumes:
      - .:/activity
    ports:
      - 8081:8080
    # network_mode: host
    networks:
      activity-net:
        ipv4_address: 172.27.1.2
    # command: ./start.sh
    depends_on:
      - database
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    # volumes:
    #   - data:/var/lib/postgresql/data
    networks:
      activity-net:
        ipv4_address: 172.27.1.3


networks:
 activity-net:
  ipam:
   driver: default
   config:
    - subnet: 172.27.0.0/16

# volumes:
#   data: