// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"activity/controller"
	"activity/repository"
	"activity/service"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from injector.go:

func InitSubActivity(db *gorm.DB) controller.SubActivityController {
	subActivityRepository := repository.NewSubActivityRepository(db)
	subActivityService := service.NewSubActivityService(subActivityRepository)
	subActivityController := controller.NewSubActivityController(subActivityService)
	return subActivityController
}

func InitActivity(db *gorm.DB) controller.ActivityController {
	activityRepository := repository.NewActivityRepository(db)
	activityService := service.NewActivityService(activityRepository)
	activityController := controller.NewActivityController(activityService)
	return activityController
}

// injector.go:

var activitySet = wire.NewSet(repository.NewActivityRepository, service.NewActivityService, controller.NewActivityController)

var subactivitySet = wire.NewSet(repository.NewSubActivityRepository, service.NewSubActivityService, controller.NewSubActivityController)
