// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"activity/controller"
	"activity/repository"
	"activity/service"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from injector.go:

func InitActivity(db *gorm.DB) controller.ActivityController {
	activityRepository := repository.NewActivityRepository(db)
	activityService := service.NewActivityService(activityRepository)
	activityController := controller.NewActivityController(activityService)
	return activityController
}

// injector.go:

var dataSet = wire.NewSet(repository.NewActivityRepository, service.NewActivityService, controller.NewActivityController)
